name: Docker build and push image to aliyun Docker

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}
          tags: ${{ env.GITHUB_SHA_SHORT }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: cp .env.example .env

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to aliyunHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_HUB_PASSWORD }}

      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: backend
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}:${{ env.GITHUB_SHA_SHORT }}-backend

      - name: Build and push the frontend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: app
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}:${{ env.GITHUB_SHA_SHORT }}-frontend

      - name: Build and push the admin dashboard container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: sh_admin
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}:${{ env.GITHUB_SHA_SHORT }}-admin

      - name: Build and push the AIO container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: aio
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: ${{ secrets.ALIYUN_DOCKER_HUB_REGISTRY }}:${{ env.GITHUB_SHA_SHORT }}-aio
